// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJKUPwmuKzbk4gRCXYNcSKbYMyGCX5_nI',
    appId: '1:293903626782:web:6470fc5fc086b5686ff40f',
    messagingSenderId: '293903626782',
    projectId: 'wall-38972',
    authDomain: 'wall-38972.firebaseapp.com',
    storageBucket: 'wall-38972.appspot.com',
    measurementId: 'G-H58TDCVK5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB16E0pH3beNhUL1ai7YHsgP8-7Wg5Siso',
    appId: '1:293903626782:android:7ccdb18f1cb58b6e6ff40f',
    messagingSenderId: '293903626782',
    projectId: 'wall-38972',
    storageBucket: 'wall-38972.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWCdbaXvNYXWq0nfTscTjUElfcYqzpoHs',
    appId: '1:293903626782:ios:5665bb6cea577a896ff40f',
    messagingSenderId: '293903626782',
    projectId: 'wall-38972',
    storageBucket: 'wall-38972.appspot.com',
    iosBundleId: 'com.example.wall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWCdbaXvNYXWq0nfTscTjUElfcYqzpoHs',
    appId: '1:293903626782:ios:5665bb6cea577a896ff40f',
    messagingSenderId: '293903626782',
    projectId: 'wall-38972',
    storageBucket: 'wall-38972.appspot.com',
    iosBundleId: 'com.example.wall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJKUPwmuKzbk4gRCXYNcSKbYMyGCX5_nI',
    appId: '1:293903626782:web:a2001a115db8954a6ff40f',
    messagingSenderId: '293903626782',
    projectId: 'wall-38972',
    authDomain: 'wall-38972.firebaseapp.com',
    storageBucket: 'wall-38972.appspot.com',
    measurementId: 'G-MVGDDK934E',
  );
}
